# Generated by Django 5.2.11 on 2026-02-18 15:05

from django.db import migrations, models
from django.utils.text import slugify


def populate_unique_slugs(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    used_slugs = set(BlogPost.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True))

    for post in BlogPost.objects.all().order_by('id'):
        base_slug = slugify(post.title) or f'post-{post.id}'
        candidate = base_slug
        counter = 2
        while candidate in used_slugs:
            candidate = f'{base_slug}-{counter}'
            counter += 1
        post.slug = candidate
        post.save(update_fields=['slug'])
        used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(populate_unique_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
